name: YouTube Shorts Bot

on:
  schedule:
    - cron: "0 12 * * *"   # Roz shaam 5:30 PM India Time
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install libraries
      run: pip install openai google-api-python-client moviepy requests

    - name: Run Bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ELEVEN_API_KEY: ${{ secrets.ELEVEN_API_KEY }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        python Facts_generator.py
        python Voice_generator.py
        python Video_generator.py
        python Upload.py
